name: Streamlit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Streamlit
        run: pip install streamlit

      - name: Run Streamlit app
        run: |
          streamlit run app.py &  # Assumes the Streamlit app is named `app.py`
          sleep 10  # Wait for the app to start

      - name: Test the Streamlit app (optional)
        run: |
          # Optional step for testing; this can be adjusted as needed
          curl http://localhost:8501

        - name: Run tests
        run: pytest _test.py
